//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CLIENTID")]
    public enum CLIENTID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLoginGameServer", Value=100)]
      RQLoginGameServer = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQAccountOperation", Value=300)]
      RQAccountOperation = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLoginGame", Value=400)]
      RQLoginGame = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQCreateRole", Value=500)]
      RQCreateRole = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQEnterGame", Value=600)]
      RQEnterGame = 600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQRoleBaseOperation", Value=5000)]
      RQRoleBaseOperation = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQUseItem", Value=5100)]
      RQUseItem = 5100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQRoleBaseOperationEnd", Value=50000)]
      RQRoleBaseOperationEnd = 50000
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SERVERID")]
    public enum SERVERID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLoginGameServer", Value=100)]
      RTLoginGameServer = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTAccountOperation", Value=300)]
      RTAccountOperation = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLoginGame", Value=400)]
      RTLoginGame = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTCreateRole", Value=500)]
      RTCreateRole = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTMainUser", Value=600)]
      RTMainUser = 600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTTimeLine", Value=700)]
      RTTimeLine = 700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTMessage", Value=800)]
      RTMessage = 800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTObject_Add", Value=900)]
      RTObject_Add = 900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTObject_Sync", Value=901)]
      RTObject_Sync = 901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTObject_Delete", Value=902)]
      RTObject_Delete = 902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTObject_Move", Value=903)]
      RTObject_Move = 903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTObject_Use", Value=910)]
      RTObject_Use = 910
    }
  
}