//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CLIENTID")]
    public enum CLIENTID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLoginCenter", Value=100)]
      RQLoginCenter = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQAccountOperation", Value=300)]
      RQAccountOperation = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQLoginGame", Value=400)]
      RQLoginGame = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQCreateRole", Value=500)]
      RQCreateRole = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RQEnterGame", Value=600)]
      RQEnterGame = 600
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SERVERID")]
    public enum SERVERID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLoginCenter", Value=100)]
      RTLoginCenter = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTAccountOperation", Value=300)]
      RTAccountOperation = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTLoginGame", Value=400)]
      RTLoginGame = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTCreateRole", Value=500)]
      RTCreateRole = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTMainUser", Value=600)]
      RTMainUser = 600
    }
  
}